mysql -u root -p12345 -D MyBnB < "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\MyBnB.ddl"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\listing.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\calendar.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\availability.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\amenities.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\has.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\user.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\host.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\renter.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\owns.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\rented.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\rating.txt"
mysqlimport -u root -p12345 --local MyBnB "C:\Users\maxwe\OneDrive\Desktop\University\CSCC43\ratings.txt"
